on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
      BUILD_TYPE: Release
      RUN_TESTS: 'true'

    steps:
      # Checkout this repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Source ROS 2 environment
        run: |
          source /opt/ros/jazzy/setup.bash
          echo "ROS 2 environment sourced"

      - name: Build ap1_msgs
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build \
          --symlink-install \
          --cmake-args -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
